//Alerts
export const ALERT_SETTED = "ALERT_SETTED";
export const ALERT_REMOVED = "ALERT_REMOVED";

//Navbar
export const MENU_TOGGLED = "MENU_TOGGLED";
export const PAGE_CHANGED = "PAGE_CHANGED";

//MixValues
export const ADMIN_DASH_LOADED = "ADMIN_DASH_LOADED";
export const TOTAL_DEBT_LOADED = "TOTAL_DEBT_LOADED";
export const STUDENTNUMBER_LOADED = "STUDENTNUMBER_LOADED";
export const INVOICENUMBER_LOADED = "INVOICENUMBER_LOADED";
export const INVOICENUMBER_CLEARED = "INVOICENUMBER_CLEARED";
export const STUDENTNUMBER_CLEARED = "STUDENTNUMBER_CLEARED";
export const VALUES_CLEARED = "VALUES_CLEARED";
export const VALUES_ERROR = "VALUES_ERROR";
export const LOADING_SPINNER_UPDATED = "LOADING_SPINNER_UPDATED";
export const PREVPAGE_UPDATED = "PREVPAGE_UPDATED";
export const SEARCH_PAGE_CHANGED = "SEARCH_PAGE_CHANGED";

//Tables
export const TABLES_CLEARED = "TABLES_CLEARED";
export const ATTGRAD_TABLE_LOADED = "ATTGRAD_TABLE_LOADED";
export const ATTGRAD_LOADIND_UPDATED = "ATTGRAD_LOADIND_UPDATED";

//User
export const USER_LOADED = "USER_LOADED";
export const USERS_LOADED = "USERS_LOADED";
export const USERSBK_LOADED = "USERSBK_LOADED";
export const USERSBK_ERROR = "USERSBK_ERROR";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const USER_UPDATED = "USER_UPDATED";
export const USER_DELETED = "USER_DELETED";
export const USERFORLIST_ADDED = "USERFORLIST_ADDED";
export const USERFROMLIST_REMOVED = "USERFROMLIST_REMOVED";
export const USER_ERROR = "USER_ERROR";
export const USERS_ERROR = "USERS_ERROR";
export const USER_CLEARED = "USER_CLEARED";
export const USERS_CLEARED = "USERS_CLEARED";
export const SEARCH_CLEARED = "SEARCH_CLEARED";
export const USERS_TYPE_CHANGED = "USERS_TYPE_CHANGED";

//Auth
export const USERAUTH_LOADED = "USERAUTH_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

//Classes
export const CLASS_LOADED = "CLASS_LOADED";
export const CLASSSTUDENTS_LOADED = "CLASSSTUDENTS_LOADED";
export const CLASSSTUDENTS_ERROR = "CLASSSTUDENTS_ERROR";
export const CLASSES_LOADED = "CLASSES_LOADED";
export const CLASS_REGISTERED = "CLASS_REGISTERED";
export const CLASS_UPDATED = "CLASS_UPDATED";
export const CLASSCATEGORY_UPDATED = "CLASSCATEGORY_UPDATED";
export const CLASS_DELETED = "CLASS_DELETED";
export const CLASSSTUDENT_ADDED = "CLASSSTUDENT_ADDED";
export const CLASSSTUDENT_REMOVED = "CLASSSTUDENT_REMOVED";
export const CLASS_ERROR = "CLASS_ERROR";
export const CLASS_CLEARED = "CLASS_CLEARED";
export const CLASSES_CLEARED = "CLASSES_CLEARED";

//Register
export const REGISTER_LOADED = "REGISTER_LOADED";
export const REGISTERS_LOADED = "REGISTERS_LOADED";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const REGISTER_CLOSED = "REGISTER_CLOSED";
export const REGISTERS_CLEARED = "REGISTERS_CLEARED";
export const REGISTER_DELETED = "REGISTER_DELETED";

//Grades
export const GRADETYPES_LOADED = "GRADETYPES_LOADED";
export const GRADETYPES_UPDATED = "GRADETYPES_UPDATED";
export const GRADETYPE_DELETED = "GRADETYPE_DELETED";
export const GRADETYPES_CLEARED = "GRADETYPES_CLEARED";
export const GRADETYPE_ERROR = "GRADETYPE_ERROR";
export const USER_GRADES_LOADED = "USER_GRADES_LOADED";
export const NEW_GRADE_REGISTERED = "NEW_GRADE_REGISTERED";
export const GRADES_DELETED = "GRADES_DELETED";
export const GRADES_UPDATED = "GRADES_UPDATED";
export const GRADES_LOADED = "GRADES_LOADED";
export const GRADES_ERROR = "GRADES_ERROR";
export const GRADES_CLEARED = "GRADES_CLEARED";

//Expences
export const EXPENCETYPES_LOADED = "EXPENCETYPES_LOADED";
export const EXPENCETYPES_UPDATED = "EXPENCETYPES_UPDATED";
export const EXPENCETYPE_DELETED = "EXPENCETYPE_DELETED";
export const EXPENCETYPES_CLEARED = "EXPENCETYPES_CLEARED";
export const EXPENCE_REGISTERED = "EXPENCE_REGISTERED";
export const EXPENCE_DELETED = "EXPENCE_DELETED";
export const TRANSACTIONS_CLEARED = "TRANSACTIONS_CLEARED";
export const EXPENCES_CLEARED = "EXPENCES_CLEARED";
export const EXPENCE_ERROR = "EXPENCE_ERROR";
export const EXPENCETYPE_ERROR = "EXPENCETYPE_ERROR";
export const TRANSACTIONS_LOADED = "TRANSACTIONS_LOADED";

//Invoices
export const INVOICE_REGISTERED = "INVOICE_REGISTERED";
export const INVOICE_ERROR = "INVOICE_ERROR";
export const INVOICE_DELETED = "INVOICE_DELETED";
export const INVOICES_LOADED = "INVOICES_LOADED";
export const INVOICE_LOADED = "INVOICE_LOADED";
export const INVOICE_CLEARED = "INVOICE_CLEARED";
export const INVOICES_CLEARED = "INVOICES_CLEARED";

//Enrollments
export const ENROLLMENT_REGISTERED = "ENROLLMENT_REGISTERED";
export const ENROLLMENT_ERROR = "ENROLLMENT_ERROR";
export const ENROLLMENTS_LOADED = "ENROLLMENTS_LOADED";
export const ENROLLMENT_CLEARED = "ENROLLMENT_CLEARED";
export const ENROLLMENTS_CLEARED = "ENROLLMENTS_CLEARED";
export const ENROLLMENT_UPDATED = "ENROLLMENT_UPDATED";
export const ENROLLMENT_LOADED = "ENROLLMENT_LOADED";
export const ENROLLMENT_DELETED = "ENROLLMENT_DELETED";

//Assistance
export const STUDENT_ATTENDANCES_LOADED = "STUDENT_ATTENDANCES_LOADED";
export const ATTENDANCES_LOADED = "ATTENDANCES_LOADED";
export const ATTENDANCES_UPDATED = "ATTENDANCES_UPDATED";
export const NEW_DATE_REGISTERED = "NEW_DATE_REGISTERED";
export const DATES_DELETED = "DATES_DELETED";
export const ATTENDANCES_ERROR = "ATTENDANCES_ERROR";
export const ATTENDANCES_CLEARED = "ATTENDANCES_CLEARED";

//Installments
export const INSTALLMENT_LOADED = "INSTALLMENT_LOADED";
export const INSTALLMENTS_LOADED = "INSTALLMENTS_LOADED";
export const USER_INSTALLMENTS_LOADED = "USER_INSTALLMENTS_LOADED";
export const INSTALLMENT_REGISTERED = "INSTALLMENT_REGISTERED";
export const INSTALLMENT_UPDATED = "INSTALLMENT_UPDATED";
export const INSTALLMENT_DELETED = "INSTALLMENT_DELETED";
export const EXPIRED_INSTALLMENTS_UPDATED = "EXPIRED_INSTALLMENTS_UPDATED";
export const INVOICE_DETAIL_ADDED = "INVOICE_DETAIL_ADDED";
export const INVOICE_DETAIL_REMOVED = "INVOICE_DETAIL_REMOVED";
export const INSTALLMENT_CLEARED = "INSTALLMENT_CLEARED";
export const INSTALLMENTS_CLEARED = "INSTALLMENTS_CLEARED";
export const USER_INSTALLMENTS_CLEARED = "USER_INSTALLMENTS_CLEARED";
export const INSTALLMENTS_ERROR = "INSTALLMENTS_ERROR";

//Towns
export const TOWNS_LOADED = "TOWNS_LOADED";
export const TOWNS_ERROR = "TOWNS_ERROR";
export const TOWNS_UPDATED = "TOWNS_UPDATED";
export const TOWN_DELETED = "TOWN_DELETED";
export const TOWNS_CLEARED = "TOWNS_CLEARED";

//Neighbourhoods
export const NEIGHBOURHOODS_LOADED = "NEIGHBOURHOODS_LOADED";
export const NEIGHBOURHOODS_ERROR = "NEIGHBOURHOODS_ERROR";
export const NEIGHBOURHOODS_UPDATED = "NEIGHBOURHOODS_UPDATED";
export const NEIGHBOURHOOD_DELETED = "NEIGHBOURHOOD_DELETED";
export const NEIGHBOURHOODS_CLEARED = "NEIGHBOURHOODS_CLEARED";

//Categories
export const CATEGORIES_LOADED = "CATEGORIES_LOADED";
export const CATEGORIES_CLEARED = "CATEGORIES_CLEARED";
export const CATEGORY_ERROR = "CATEGORY_ERROR";
export const CATEGORIES_UPDATED = "CATEGORIES_UPDATED";

//Posts
export const POST_LOADED = "POST_LOADED";
export const POSTS_LOADED = "POSTS_LOADED";
export const POST_ERROR = "POST_ERROR";
export const LIKES_UPDATED = "LIKES_UPDATED";
export const POST_DELETED = "POST_DELETED";
export const POST_ADDED = "POST_ADDED";
export const COMMENT_ADDED = "COMMENT_ADDED";
export const COMMENT_DELETED = "COMMENT_DELETED";
export const POSTS_CLEARED = "POSTS_CLEARED";
export const POST_CLEARED = "POST_CLEARED";

//Penalty
export const PENALTY_LOADED = "PENALTY_LOADED";
export const PENALTY_CLEARED = "PENALTY_CLEARED";
export const PENALTY_ERROR = "PENALTY_ERROR";
export const PENALTY_REGISTERED = "PENALTY_REGISTERED";
